[package]
name = "send_message"
version = "1.0.0"
authors = []

[addresses]
MyModule = '0x062cd764b99f30bce1c6d100370ccbf9379db257e085020a650a4cef6c447bfc'
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "testnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]